server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tiku?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: xzlyf297
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    timeout: 30000
    database: 0
    lettuce: #lettuce基于netty，线程安全，支持并发
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 2
        min-idle: 0
      cluster:
        refresh:
          adaptive: true
          period: 60
  mvc:
    static-path-pattern: /**
  jackson:
    default-property-inclusion: non_null  #返回数据时过滤null字段
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath:mappers/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰命名和下划线自动转换
